name: Releases

on:
  workflow_call:
    inputs:
      package:
        type: string
        required: true
        description: "Package or app to release"
  workflow_dispatch:
    inputs:
      package:
        description: "Package or app to release"
        required: true
        type: choice
        options:
          - packages/ui
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  stable_release:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call'
    name: Stable
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      statuses: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        run: npm install -g pnpm@9.1.3
        shell: bash

      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: lts/iron
          registry-url: "https://registry.npmjs.org"
          always-auth: true

      - run: pnpm install
        shell: bash

      - run: pnpm changeset:version ${{ github.event.inputs.package }}
        shell: bash

      - name: Create Release Pull Request or Publish to npm for ${{ github.event.inputs.package }}
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm changeset:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  auto_release:
    if: github.event_name == 'push'
    name: Unstable
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        run: npm install -g pnpm@9.1.3
        shell: bash

      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: lts/iron
          registry-url: "https://registry.npmjs.org"
          always-auth: true

      - run: pnpm install
        shell: bash

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset:version unstable
          publish: pnpm changeset:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
