name: Releases

on:
  workflow_call:
    inputs:
      package:
        type: string
        required: true
        description: "Package or app to release"
  workflow_dispatch:
    inputs:
      package:
        description: "Package or app to release"
        required: true
        type: choice
        options:
          - packages/ui
  push:
    branches:
      - main
      - release/**

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  DO_NOT_TRACK: 1

jobs:
  stable_release:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call'
    name: Create stable release PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        run: npm install -g pnpm@9.1.3

      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: lts/iron
          registry-url: "https://registry.npmjs.org"
          always-auth: true

      - run: pnpm install

      - name: get package name
        run: echo "name=$(cat package.json | jq -r '.name')" >> "$GITHUB_OUTPUT"
        working-directory: ${{ github.event.inputs.package }}
        id: pkg

      - name: exit pre state
        run: pnpm changeset pre exit

      - name: Create Release Pull Request for ${{ github.event.inputs.package }}
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset:version ${{ github.event.inputs.package }}
          title: "${{ steps.pkg.outputs.name }}: release stable version"
          commit: "chore(${{ steps.pkg.outputs.name }}): stable release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  auto_release:
    if: github.event_name == 'push'
    name: Publish or Create pre-release PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        run: npm install -g pnpm@9.1.3

      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: lts/iron
          registry-url: "https://registry.npmjs.org"
          always-auth: true

      - run: pnpm install

      - name: get changeset pre mode
        id: changeset-status
        # if changeset is not in pre mode, try to publish
        run: echo "mode=$(cat .changeset/pre.json | jq -r '.mode')" >> "$GITHUB_OUTPUT"

      - name: release for stable
        if: steps.changeset-status.outputs.mode == 'exit'
        run: pnpm changeset:release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset:version unstable
          publish: pnpm changeset:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
