name: Release packages

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    environment:
      name: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        run: npm install -g pnpm@9.1.3
        shell: bash

      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: lts/iron
          registry-url: "https://registry.npmjs.org"
          always-auth: true

      - run: pnpm install
        shell: bash

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
